name: Flask Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy in EC2
      env:
        PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        HOST_NAME: ${{ secrets.HOST_NAME }}
        USER_NAME: ${{ secrets.USER_NAME }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} "
          cd Flask-Deployment/ &&
          git pull &&
          sudo systemctl stop flask-app &&
          sudo systemctl daemon-reload &&
          sudo systemctl start flask-app
        "

        
